### PR TITLE
cleanup & depend on global/document

### PR DESCRIPTION
**Pull request by kuraga**
Let's try one more time? See also #5 and 55cd474cec4ce8dd55699a5c058d3cdae13bb1a7

### CODE REVIEW

**Comment by kuraga** [comment]
@defunctzombie broken but it doesn't depend on this PR

**Comment by defunctzombie** [comment]
I don't see the point.

**Comment by kuraga** [comment]
@defunctzombie what do you mean?

**Comment by kuraga** [comment]
@defunctzombie if you talk about tests then [here](https://travis-ci.org/defunctzombie/synthetic-dom-events/builds/52517217) we see
```
Error:
Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.
```
It's not specific tis PR. Thanks.

**Comment by defunctzombie** [comment]
Sorry, ```I don't see the point``` was referring to using the global module instead of the global variable.

**Comment by kuraga** [comment]
I think because we don't have `document` in NodeJS/io.js and can't use your tool on server.
@Raynos , correct?

**Comment by Raynos** [comment]
Yeah the point is to import `document` from a module that implements `document` in browser and fake `document` in node.

This means you can run your entire browser unit tests in node against a minimal fake `document`.

**Comment by defunctzombie** [comment]
Personally I don't want to include all the stuff in this file:
https://github.com/Raynos/global/blob/master/document.js which seems not that useful in a browser.

Also, there is no way I will allow dependencies that are using `^` or depending on things using `^` or `~` for this module. Sorry.

I understand the use case for using this in node (for whatever experiments/practical needs), but the required module would need to be leaner for the browser use case if possible. Then I am ok using it.

**Comment by Raynos** [comment]
@defunctzombie 

https://github.com/Raynos/global/blob/master/package.json#L19-L22 Those dependencies are no ops.

You are including a small amount of static weight because the file is 15 lines.

**Comment by defunctzombie** [comment]
Why not just have a browser field entry for "document.js" then if anyone requires it, you can just have a file that exports window.document

**Comment by Raynos** [comment]
@defunctzombie I tried that. Could not get it to work :/

**Comment by nikuda** [comment]
Any progress on this patch?

**Comment by bendrucker** [comment]
synthetic-dom-events is currently 1.25k minified and gzipped and would become 1.32k with this change

**Comment by defunctzombie** [comment]
Do not think this is necessary. If you want to use outside of browser, you can easily shim/polyfill these to whatever you need.

**Pull request closed without merging**
